# USA Facts Data Cleaning

### Two of the USA Facts datasets need to be cleaned for use within Tableau.
First we will import them and create our two data frames.

In [1]:
import pandas as pd
import datetime as dt

path = r"C:\Users\Basil\Documents\Data Science\Projects\20200506 Coronavirus\1. Original Data\covid_confirmed_usafacts.csv"
df = pd.read_csv(path)

path2 = r"C:\Users\Basil\Documents\Data Science\Projects\20200506 Coronavirus\1. Original Data\covid_deaths_usafacts.csv"
df2 = pd.read_csv(path2)

In [2]:
df.head(5)

,countyFIPS,County Name,State,stateFIPS,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,5/16/20,5/17/20,5/18/20,5/19/20,5/20/20,5/21/20,5/22/20,5/23/20,5/24/20,5/25/20
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,110,110,120,127,136,147,149,155,159,173
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,254,254,260,262,270,270,271,273,274,276
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,79,81,85,90,96,100,104,105,110,116
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,50,50,50,51,52,52,55,58,59,62

After viewing the first five rows we can see that the first dataset is in long form. We will melt data.

In [3]:
clean_df = pd.melt(df,
                       ["countyFIPS", "County Name", "State", "stateFIPS"],
                       var_name="Date",
                       value_name="Confirmed Cases")

In [4]:
clean_df.head(10)

,countyFIPS,County Name,State,stateFIPS,Date,Confirmed Cases
0,0,Statewide Unallocated,AL,1,1/22/20,0
1,1001,Autauga County,AL,1,1/22/20,0
2,1003,Baldwin County,AL,1,1/22/20,0
3,1005,Barbour County,AL,1,1/22/20,0
4,1007,Bibb County,AL,1,1/22/20,0
5,1009,Blount County,AL,1,1/22/20,0
6,1011,Bullock County,AL,1,1/22/20,0
7,1013,Butler County,AL,1,1/22/20,0
8,1015,Calhoun County,AL,1,1/22/20,0
9,1017,Chambers County,AL,1,1/22/20,0

Now that the data is in long form we will change the state abbreviations to long form so that it will join properly with our Kaiser Permanente dataset.

In [5]:
clean_df = clean_df.replace({"State" : {"AL" : "Alabama", 
                                "AK" : "Alaska", 
                                "AZ" : "Arizona",
                                "AR" : "Arkansas",
                                "CA" : "California",
                                "CO" : "Colorado",
                                "CT" : "Connecticut",
                                "DE" : "Delaware",
                                "DC" : "District of Columbia",
                                "FL" : "Florida",
                                "GA" : "Georgia",
                                "HI" : "Hawaii",
                                "ID" : "Idaho",
                                "IL" : "Illinois",
                                "IN" : "Indiana",
                                "IA" : "Iowa",
                                "KS" : "Kansas",
                                "KY" : "Kentucky",
                                "LA" : "Louisiana",
                                "ME" : "Maine",
                                "MD" : "Maryland",
                                "MA" : "Massachusetts",
                                "MI" : "Michigan",
                                "MN" : "Minnesota",
                                "MS" : "Mississippi",
                                "MO" : "Missouri",
                                "MT" : "Montana",
                                "NE" : "Nebraska",
                                "NV" : "Nevada",
                                "NH" : "New Hampshire",
                                "NJ" : "New Jersey",
                                "NM" : "New Mexico",
                                "NY" : "New York",
                                "NC" : "North Carolina",
                                "ND" : "North Dakota",
                                "OH" : "Ohio",
                                "OK" : "Oklahoma",
                                "OR" : "Oregon",
                                "PA" : "Pennsylvania",
                                "RI" : "Rhode Island",
                                "SC" : "South Carolina",
                                "SD" : "South Dakota",
                                "TN" : "Tennessee",
                                "TX" : "Texas",
                                "UT" : "Utah",
                                "VT" : "Vermont",
                                "VA" : "Virginia",
                                "WA" : "Washington",
                                "WV" : "West Virginia",
                                "WI" : "Wisconsin",
                                "WY" : "Wyoming"}})

We then will change some of the county data to align with their Tableau recognized names. We will also move the Grand Princess Cruise Ship and New York City Unallocated to the statewide unallocated categories.

In [6]:
clean_df = clean_df.replace({"County Name" : {"Broomfield County and City" : "Broomfield",
                                              "City of St. Louis" : "St. Louis City",
                                              "Grand Princess Cruise Ship" : "Statewide Unallocated",
                                              "New York City Unallocated/Probable" : "Statewide Unallocated",
                                              "Jackson County (including other portions of Kansas City)" : "Jackson County",
                                              "Matthews County" : "Mathews County",
                                              "Municipality of Anchorage" : "Anchorage",
                                              "Washington" : "District of Columbia",
                                              "City and Borough of Juneau" : "Juneau"}})

In [7]:
clean_df.head(5)

,countyFIPS,County Name,State,stateFIPS,Date,Confirmed Cases
0,0,Statewide Unallocated,Alabama,1,1/22/20,0
1,1001,Autauga County,Alabama,1,1/22/20,0
2,1003,Baldwin County,Alabama,1,1/22/20,0
3,1005,Barbour County,Alabama,1,1/22/20,0
4,1007,Bibb County,Alabama,1,1/22/20,0

Now that the data is tidy we are saving it into csv file.

In [8]:
save_path = r"C:\Users\Basil\Documents\Data Science\Projects\20200506 Coronavirus\2. Prepared Data\covid19.csv"
clean_df.to_csv(save_path)

In [9]:
df2.head(5)

,countyFIPS,County Name,State,stateFIPS,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,5/16/20,5/17/20,5/18/20,5/19/20,5/20/20,5/21/20,5/22/20,5/23/20,5/24/20,5/25/20
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,8,8,8,8,8,8,9,9,9,9
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1

Like our confirmed cases file our total deaths file also will need to be melted for analysis in tableau.

In [11]:
clean_df2 = pd.melt(df2,
                       ["countyFIPS", "County Name", "State", "stateFIPS"],
                       var_name="Date",
                       value_name="Deaths")

In [12]:
clean_df2.head(10)

   countyFIPS            County Name State  stateFIPS     Date  Deaths
0           0  Statewide Unallocated    AL          1  1/22/20       0
1        1001         Autauga County    AL          1  1/22/20       0
2        1003         Baldwin County    AL          1  1/22/20       0
3        1005         Barbour County    AL          1  1/22/20       0
4        1007            Bibb County    AL          1  1/22/20       0
5        1009          Blount County    AL          1  1/22/20       0
6        1011         Bullock County    AL          1  1/22/20       0
7        1013          Butler County    AL          1  1/22/20       0
8        1015         Calhoun County    AL          1  1/22/20       0
9        1017        Chambers County    AL          1  1/22/20       0

Since our cases file will be used to join other data sets we dont need to change anything else before analysis. So we save the dataframe into a csv file.

In [13]:
save_path2 = r"C:\Users\Basil\Documents\Data Science\Projects\20200506 Coronavirus\2. Prepared Data\covid19_deaths.csv"
clean_df2.to_csv(save_path2)